// This file was generated by Firebase Studio.
'use server';
/**
 * @fileOverview Passport data extraction AI agent.
 *
 * - extractPassportData - A function that handles the passport data extraction process.
 * - ExtractPassportDataInput - The input type for the extractPassportData function.
 * - ExtractPassportDataOutput - The return type for the extractPassportData function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const ExtractPassportDataInputSchema = z.object({
  photoUrl: z.string().describe('The URL of the passport photo.'),
});
export type ExtractPassportDataInput = z.infer<typeof ExtractPassportDataInputSchema>;

const ExtractPassportDataOutputSchema = z.object({
  fullName: z.string().describe('The full name of the passport holder.'),
  passportNumber: z.string().describe('The passport number.'),
  dateOfBirth: z.string().describe('The date of birth of the passport holder.'),
  dateOfExpiry: z.string().describe('The date of expiry of the passport.'),
  issuingCountry: z.string().describe('The issuing country of the passport.'),
});
export type ExtractPassportDataOutput = z.infer<typeof ExtractPassportDataOutputSchema>;

export async function extractPassportData(input: ExtractPassportDataInput): Promise<ExtractPassportDataOutput> {
  return extractPassportDataFlow(input);
}

const prompt = ai.definePrompt({
  name: 'extractPassportDataPrompt',
  input: {
    schema: z.object({
      photoUrl: z.string().describe('The URL of the passport photo.'),
    }),
  },
  output: {
    schema: z.object({
      fullName: z.string().describe('The full name of the passport holder.'),
      passportNumber: z.string().describe('The passport number.'),
      dateOfBirth: z.string().describe('The date of birth of the passport holder.'),
      dateOfExpiry: z.string().describe('The date of expiry of the passport.'),
      issuingCountry: z.string().describe('The issuing country of the passport.'),
    }),
  },
  prompt: `You are an expert in extracting data from passports. Please extract the following information from the passport image. If you can't find a specific field, return "N/A".

Full Name: The full name of the passport holder.
Passport Number: The passport number.
Date of Birth: The date of birth of the passport holder.
Date of Expiry: The date of expiry of the passport.
Issuing Country: The issuing country of the passport.

Passport Image: {{media url=photoUrl}}

Return the information in JSON format.
`,
});

const extractPassportDataFlow = ai.defineFlow<
  typeof ExtractPassportDataInputSchema,
  typeof ExtractPassportDataOutputSchema
>({
  name: 'extractPassportDataFlow',
  inputSchema: ExtractPassportDataInputSchema,
  outputSchema: ExtractPassportDataOutputSchema,
}, async input => {
  const {output} = await prompt(input);
  return output!;
});
